engines:
  checkstyle:
    enabled: true
    channel: "beta"
    checks:
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck:
        enabled: true
        option: alone_or_singleline
  pmd:
    enabled: true
    channel: "beta"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.java"
  - "**.md"
exclude_paths: []
